### Develop LSTM Models For Univariate Time Series Forecasting

In [2]:
#univariate lstm
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Flatten, Dense, Input

In [4]:
# prepareindependent and dependent features
def prepare_data(timeseries_data, n_features):
	X, y =[],[]
	for i in range(len(timeseries_data)):
		# find the end of this pattern
		end_ix = i + n_features
		# check if we are beyond the sequence
		if end_ix > len(timeseries_data)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [6]:
# define input sequence
timeseries_data = [110, 125, 133, 146, 158, 172, 187, 196, 210]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = prepare_data(timeseries_data, n_steps)

In [8]:
print(X),print(y)

[[110 125 133]
 [125 133 146]
 [133 146 158]
 [146 158 172]
 [158 172 187]
 [172 187 196]]
[146 158 172 187 196 210]


(None, None)

In [10]:
X.shape

(6, 3)

In [12]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

### Building LSTM Model

In [15]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=300, verbose=1)

Epoch 1/300


/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 999ms/step - loss: 28687.5762
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 27612.7285
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26863.8672
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26170.5840
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 25455.9863
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 24703.9902
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 23927.0859
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 23167.9746
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 22408.7441
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 21571.1289
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 20615.5801
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 19572.6973
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 18495.5312
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 17394.3301
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s

### Predicting For the next 10 data

In [24]:
# demonstrate prediction for next 10 days
import numpy as np
x_input = np.array([187, 196, 210])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<10):
    
    if(len(temp_input)>3):
        x_input=nparray(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

[222.66788]


NameError: name 'array' is not defined